### ISSUE TITLE
Question: Are you planning to release a double consistent hash algorhithm for yanet?

### ISSUE THREAD

**Issue by urbanchef** [yanet-platform/yanet#140]
Reference: https://youtu.be/t3TaXBU4Bn8?si=hCF8KLWrRCXB1T6W

**Comment by GeorgyKirichenko** [comment]
Hi Roman!

Yes, we are thinking about consistent hashing for YANET balancer in the near future, my expectations this could be implemented until the end of 2024.

**Comment by GeorgyKirichenko** [comment]
#33 is about consistent hashing so I would like to link the reference you provided and close the issue as duplicate.

**Comment by GeorgyKirichenko** [comment]
Duplicates #33
