### ISSUE TITLE
stl_vector

### ISSUE THREAD

**Issue by Denyme** [yanet-platform/yanet#196]
hi.
when i try add static route line yanet-cli rib static insert default x.x.x.x/28 x.x.x.x get error:
/usr/include/c++/9/bits/stl_vector.h:1060: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::vector<_Tp, _Alloc>::const_reference = const unsigned char&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)

**Comment by Denyme** [comment]
config typical from demo, but use balancer, not firewall

**Comment by GeorgyKirichenko** [comment]
Hi and thanks for the report!
We are starting to work on the issue reproduction and will return with update soon.

Could you provide us with your system specification (CPU network card and memory should be enough). It would be great to see output of the following commands:
- `cat /proc/cpuinfo`
- `cat /proc/meminfo`
- `lspci -v`

**Comment by Denyme** [comment]
[cpu.txt](https://github.com/yanet-platform/yanet/files/15452791/cpu.txt)
[meminfo.txt](https://github.com/yanet-platform/yanet/files/15452792/meminfo.txt)
[pci.txt](https://github.com/yanet-platform/yanet/files/15452793/pci.txt)
